draw_text(0, 0, "throttle " + string(throttle))
draw_text(0, 15, "thrust " + string(maxThrust * thrustCurve[throttle]))
draw_text(0, 30, "drag " + string(drag))
draw_text(0, 45, "acceleration " + string(acceleration))
draw_text(0, 60, "speed " + string(speed))
draw_text(0, 75, "turnSlowdown " + string(turnSlowdown))
draw_text(0, 90, "turnRate " + string(turnRate))
draw_text(0, 105, "direction " + string(direction))
draw_text(0, 120, "position (" + string(x) + ", " + string(y) + ")")
